name: Calculate CI Failure Rate for Specific Workflow

on:
  schedule:
    - cron: '0 0 * * *' # Run daily at midnight UTC
  workflow_dispatch: # Allow manual triggering of the workflow

jobs:
  calculate-failure-rate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Calculate CI failure rate for 'test-go.yaml' workflow in the last day
      uses: actions/github-script@v6
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        script: |
          const owner = 'fleetdm';
          const repo = 'fleet';
          const workflow_id = 'test-go.yaml';
          const since = new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString();

          let failureCount = 0;
          let totalCount = 0;

          // Fetch workflow runs for the specified workflow ID in the last day
          const workflowRuns = await github.rest.actions.listWorkflowRuns({
            owner,
            repo,
            workflow_id,
            per_page: 100,
          });

          for (const run of workflowRuns.data.workflow_runs) {
            // Filter runs that were created earlier than the target date
            if (new Date(run.created_at) < new Date(since)) continue;

            totalCount++;
            if (run.conclusion === 'failure') {
              failureCount++;
            }
          }

          const failureRate = totalCount > 0 ? (failureCount / totalCount) * 100 : 0;

          console.log(`Total Workflow Runs: ${totalCount}`);
          console.log(`Failed Workflow Runs: ${failureCount}`);
          console.log(`Failure Rate: ${failureRate.toFixed(2)}%`);
