name: Calculate CI Failure Rate

on:
  schedule:
    - cron: '0 0 * * *' # Run daily at midnight UTC
  workflow_dispatch: # Allow manual triggering of the workflow

jobs:
  calculate-failure-rate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Calculate CI failure rate for the last day
      uses: actions/github-script@v6
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        script: |
          const owner = 'fleetdm';
          const repo = 'fleet';
          const since = new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString();

          let failureCount = 0;
          let totalCount = 0;

          // Fetch all PRs from the last day
          const pullRequests = await github.rest.pulls.list({
            owner,
            repo,
            state: 'all',
            sort: 'created',
            direction: 'desc',
            per_page: 100,
          });

          for (const pr of pullRequests.data) {
            // Filter out PRs that were created earlier than the target date
            if (new Date(pr.created_at) < new Date(since)) continue;

            // Get the check runs for each PR's latest commit
            const checkRuns = await github.rest.checks.listForRef({
              owner,
              repo,
              ref: pr.head.sha,
            });

            for (const check of checkRuns.data.check_runs) {
              totalCount++;
              if (check.conclusion === 'failure') {
                failureCount++;
              }
            }
          }

          const failureRate = totalCount > 0 ? (failureCount / totalCount) * 100 : 0;

          console.log(`Total CI Runs: ${totalCount}`);
          console.log(`Failed CI Runs: ${failureCount}`);
          console.log(`Failure Rate: ${failureRate.toFixed(2)}%`);
